### ISSUE TITLE
TI 84+ not working with site?

### ISSUE THREAD

**Issue by arusher999** [Timendus/ticalc-usb#35]
## Device information

{
  "deviceClass": 0,
  "deviceProtocol": 0,
  "deviceSubclass": 0,
  "deviceVersionMajor": 1,
  "deviceVersionMinor": 0,
  "deviceVersionSubminor": 0,
  "manufacturerName": null,
  "productId": 33535,
  "productName": null,
  "serialNumber": "B30F0841D9E2",
  "usbVersionMajor": 2,
  "usbVersionMinor": 0,
  "usbVersionSubminor": 1,
  "vendorId": 1105
}

## Additional information

Please provide this extra information so we can better support your calculator:

Calculator name as written on the device: Ti 84+
This calculator can also receive files made for these other types of calculators:  I don't know?
Any other technical information that might help: Using Chrome/ Opera GX on Win 10, shows up as "unknown device from texas instruments.

**Comment by Timendus** [comment]
Yeah, your `productId` makes no sense and your `productName` is empty @arusher999. That looks like an issue with your calculator. https://ticalc.link has a "catch all" feature that looks only at the `vendorID`, otherwise your device wouldn't have shown up at all.

Does it work in other link software? Did you try resetting the device?

I'm going to close this issue for now, as this is not a fault of the software. Feel free to open a new issue if you run into any other problems, or [start a discussion](https://github.com/Timendus/ticalc-usb/discussions/new) if you need help with your device.
